language: python
python:
  - 2.7
  - 3.4
env:
  - DJANGO_VERSION=1.8.8
  - DJANGO_VERSION=1.6.11
install:
  - pip install flake8
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py install
before_script:
   flake8 codespeed
script:
  - python setup.py test
  - python manage.py test codespeed
